/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerSubmitResult {
  'feedback' : string,
  'score' : bigint,
  'finalScore' : [] | [bigint],
  'nextQuestion' : [] | [InterviewQuestion],
  'sessionComplete' : boolean,
}
export type Difficulty = { 'Easy' : null } |
  { 'Hard' : null } |
  { 'Medium' : null };
export interface EducationEntry {
  'gpa' : [] | [string],
  'field' : string,
  'startYear' : bigint,
  'endYear' : [] | [bigint],
  'institution' : string,
  'degree' : string,
}
export interface ExperienceEntry {
  'title' : string,
  'endDate' : [] | [string],
  'description' : string,
  'company' : string,
  'achievements' : Array<string>,
  'startDate' : string,
}
export type ExperienceLevel = { 'Mid' : null } |
  { 'Junior' : null } |
  { 'Senior' : null };
export interface InterviewQuestion {
  'id' : QuestionId,
  'idealAnswer' : string,
  'question' : string,
  'rubric' : ScoringRubric,
  'difficulty' : Difficulty,
  'role' : UserRole,
  'tags' : Array<string>,
  'questionType' : QuestionType,
}
export interface LearningLink {
  'url' : string,
  'title' : string,
  'resourceType' : string,
}
export interface MockSession {
  'id' : SessionId,
  'completedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'turns' : Array<MockSessionTurn>,
  'userId' : UserId,
  'difficulty' : Difficulty,
  'role' : UserRole,
  'totalScore' : bigint,
  'questionIds' : Array<QuestionId>,
  'currentQuestionIndex' : bigint,
  'isComplete' : boolean,
}
export interface MockSessionTurn {
  'question' : string,
  'userAnswer' : string,
  'feedback' : string,
  'score' : bigint,
  'questionId' : QuestionId,
  'answeredAt' : Timestamp,
}
export interface ProgressReport {
  'scoreTrends' : Array<ScoreTrend>,
  'topicsTotal' : bigint,
  'readinessScore' : bigint,
  'skillsAcquired' : Array<string>,
  'userId' : UserId,
  'lastUpdated' : Timestamp,
  'mockSessionsCompleted' : bigint,
  'topicsCompleted' : bigint,
  'averageScore' : bigint,
}
export type QuestionId = bigint;
export type QuestionType = { 'Technical' : null } |
  { 'Behavioral' : null };
export interface ResumeData {
  'userId' : UserId,
  'education' : Array<EducationEntry>,
  'experience' : Array<ExperienceEntry>,
  'summary' : string,
  'updatedAt' : Timestamp,
  'targetRole' : string,
  'skills' : Array<string>,
}
export interface ResumeGenerationResult {
  'resume' : ResumeData,
  'suggestions' : Array<string>,
  'isDemo' : boolean,
  'keywords' : Array<string>,
}
export interface ResumeInput {
  'education' : Array<EducationEntry>,
  'experience' : Array<ExperienceEntry>,
  'summary' : string,
  'targetRole' : string,
  'skills' : Array<string>,
}
export interface ScoreTrend {
  'completedAt' : Timestamp,
  'score' : bigint,
  'sessionId' : SessionId,
}
export interface ScoringRubric {
  'fair' : string,
  'good' : string,
  'poor' : string,
  'excellent' : string,
}
export type SessionId = bigint;
export interface SessionStartResult {
  'firstQuestion' : InterviewQuestion,
  'sessionId' : SessionId,
}
export interface SkillGapEntry {
  'targetLevel' : bigint,
  'studyResources' : Array<string>,
  'skill' : string,
  'currentLevel' : bigint,
  'priority' : bigint,
}
export interface SkillGapResult {
  'studyPlan' : Array<StudyPlanItem>,
  'weakSkills' : Array<SkillGapEntry>,
  'overallReadiness' : bigint,
}
export interface StudyPlanItem {
  'topicIds' : Array<TopicId>,
  'skill' : string,
  'estimatedHours' : bigint,
  'priority' : bigint,
}
export interface StudyTopic {
  'id' : TopicId,
  'name' : string,
  'role' : UserRole,
  'description' : string,
  'subtopics' : Array<Subtopic>,
  'priority' : bigint,
}
export interface Subtopic {
  'name' : string,
  'description' : string,
  'links' : Array<LearningLink>,
}
export type Timestamp = bigint;
export type TopicId = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'experienceLevel' : ExperienceLevel,
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'onboardingComplete' : boolean,
  'updatedAt' : Timestamp,
  'targetJobTitle' : string,
}
export interface UserProfileInput {
  'experienceLevel' : ExperienceLevel,
  'name' : string,
  'role' : UserRole,
  'targetJobTitle' : string,
}
export type UserRole = { 'ProductManager' : null } |
  { 'DataAnalyst' : null } |
  { 'DataScientist' : null } |
  { 'BackendDeveloper' : null } |
  { 'FrontendDeveloper' : null } |
  { 'FullStack' : null } |
  { 'DevOps' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserTopicProgress {
  'completedAt' : [] | [Timestamp],
  'userId' : UserId,
  'completed' : boolean,
  'topicId' : TopicId,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'completeOnboarding' : ActorMethod<[], undefined>,
  'generateResume' : ActorMethod<[ResumeInput], ResumeGenerationResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getInterviewQuestions' : ActorMethod<
    [UserRole, [] | [Difficulty]],
    Array<InterviewQuestion>
  >,
  'getMockSession' : ActorMethod<[SessionId], [] | [MockSession]>,
  'getProgressReport' : ActorMethod<[], ProgressReport>,
  'getResume' : ActorMethod<[], [] | [ResumeData]>,
  'getSkillGapAnalysis' : ActorMethod<[], SkillGapResult>,
  'getStudyTopic' : ActorMethod<[TopicId], [] | [StudyTopic]>,
  'getStudyTopics' : ActorMethod<[UserRole], Array<StudyTopic>>,
  'getUserMockSessions' : ActorMethod<[], Array<MockSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTopicProgress' : ActorMethod<[], Array<UserTopicProgress>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTopicComplete' : ActorMethod<[TopicId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], UserProfile>,
  'saveResume' : ActorMethod<[ResumeInput], ResumeData>,
  'startMockSession' : ActorMethod<[UserRole, Difficulty], SessionStartResult>,
  'submitAnswer' : ActorMethod<[SessionId, string], AnswerSubmitResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];