/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EducationEntry = IDL.Record({
  'gpa' : IDL.Opt(IDL.Text),
  'field' : IDL.Text,
  'startYear' : IDL.Nat,
  'endYear' : IDL.Opt(IDL.Nat),
  'institution' : IDL.Text,
  'degree' : IDL.Text,
});
export const ExperienceEntry = IDL.Record({
  'title' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'company' : IDL.Text,
  'achievements' : IDL.Vec(IDL.Text),
  'startDate' : IDL.Text,
});
export const ResumeInput = IDL.Record({
  'education' : IDL.Vec(EducationEntry),
  'experience' : IDL.Vec(ExperienceEntry),
  'summary' : IDL.Text,
  'targetRole' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ResumeData = IDL.Record({
  'userId' : UserId,
  'education' : IDL.Vec(EducationEntry),
  'experience' : IDL.Vec(ExperienceEntry),
  'summary' : IDL.Text,
  'updatedAt' : Timestamp,
  'targetRole' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const ResumeGenerationResult = IDL.Record({
  'resume' : ResumeData,
  'suggestions' : IDL.Vec(IDL.Text),
  'isDemo' : IDL.Bool,
  'keywords' : IDL.Vec(IDL.Text),
});
export const ExperienceLevel = IDL.Variant({
  'Mid' : IDL.Null,
  'Junior' : IDL.Null,
  'Senior' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'ProductManager' : IDL.Null,
  'DataAnalyst' : IDL.Null,
  'DataScientist' : IDL.Null,
  'BackendDeveloper' : IDL.Null,
  'FrontendDeveloper' : IDL.Null,
  'FullStack' : IDL.Null,
  'DevOps' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'experienceLevel' : ExperienceLevel,
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'onboardingComplete' : IDL.Bool,
  'updatedAt' : Timestamp,
  'targetJobTitle' : IDL.Text,
});
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Hard' : IDL.Null,
  'Medium' : IDL.Null,
});
export const QuestionId = IDL.Nat;
export const ScoringRubric = IDL.Record({
  'fair' : IDL.Text,
  'good' : IDL.Text,
  'poor' : IDL.Text,
  'excellent' : IDL.Text,
});
export const QuestionType = IDL.Variant({
  'Technical' : IDL.Null,
  'Behavioral' : IDL.Null,
});
export const InterviewQuestion = IDL.Record({
  'id' : QuestionId,
  'idealAnswer' : IDL.Text,
  'question' : IDL.Text,
  'rubric' : ScoringRubric,
  'difficulty' : Difficulty,
  'role' : UserRole,
  'tags' : IDL.Vec(IDL.Text),
  'questionType' : QuestionType,
});
export const SessionId = IDL.Nat;
export const MockSessionTurn = IDL.Record({
  'question' : IDL.Text,
  'userAnswer' : IDL.Text,
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'questionId' : QuestionId,
  'answeredAt' : Timestamp,
});
export const MockSession = IDL.Record({
  'id' : SessionId,
  'completedAt' : IDL.Opt(Timestamp),
  'startedAt' : Timestamp,
  'turns' : IDL.Vec(MockSessionTurn),
  'userId' : UserId,
  'difficulty' : Difficulty,
  'role' : UserRole,
  'totalScore' : IDL.Nat,
  'questionIds' : IDL.Vec(QuestionId),
  'currentQuestionIndex' : IDL.Nat,
  'isComplete' : IDL.Bool,
});
export const ScoreTrend = IDL.Record({
  'completedAt' : Timestamp,
  'score' : IDL.Nat,
  'sessionId' : SessionId,
});
export const ProgressReport = IDL.Record({
  'scoreTrends' : IDL.Vec(ScoreTrend),
  'topicsTotal' : IDL.Nat,
  'readinessScore' : IDL.Nat,
  'skillsAcquired' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'lastUpdated' : Timestamp,
  'mockSessionsCompleted' : IDL.Nat,
  'topicsCompleted' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const TopicId = IDL.Nat;
export const StudyPlanItem = IDL.Record({
  'topicIds' : IDL.Vec(TopicId),
  'skill' : IDL.Text,
  'estimatedHours' : IDL.Nat,
  'priority' : IDL.Nat,
});
export const SkillGapEntry = IDL.Record({
  'targetLevel' : IDL.Nat,
  'studyResources' : IDL.Vec(IDL.Text),
  'skill' : IDL.Text,
  'currentLevel' : IDL.Nat,
  'priority' : IDL.Nat,
});
export const SkillGapResult = IDL.Record({
  'studyPlan' : IDL.Vec(StudyPlanItem),
  'weakSkills' : IDL.Vec(SkillGapEntry),
  'overallReadiness' : IDL.Nat,
});
export const LearningLink = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'resourceType' : IDL.Text,
});
export const Subtopic = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'links' : IDL.Vec(LearningLink),
});
export const StudyTopic = IDL.Record({
  'id' : TopicId,
  'name' : IDL.Text,
  'role' : UserRole,
  'description' : IDL.Text,
  'subtopics' : IDL.Vec(Subtopic),
  'priority' : IDL.Nat,
});
export const UserTopicProgress = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'completed' : IDL.Bool,
  'topicId' : TopicId,
});
export const UserProfileInput = IDL.Record({
  'experienceLevel' : ExperienceLevel,
  'name' : IDL.Text,
  'role' : UserRole,
  'targetJobTitle' : IDL.Text,
});
export const SessionStartResult = IDL.Record({
  'firstQuestion' : InterviewQuestion,
  'sessionId' : SessionId,
});
export const AnswerSubmitResult = IDL.Record({
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'finalScore' : IDL.Opt(IDL.Nat),
  'nextQuestion' : IDL.Opt(InterviewQuestion),
  'sessionComplete' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'completeOnboarding' : IDL.Func([], [], []),
  'generateResume' : IDL.Func([ResumeInput], [ResumeGenerationResult], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getInterviewQuestions' : IDL.Func(
      [UserRole, IDL.Opt(Difficulty)],
      [IDL.Vec(InterviewQuestion)],
      ['query'],
    ),
  'getMockSession' : IDL.Func([SessionId], [IDL.Opt(MockSession)], ['query']),
  'getProgressReport' : IDL.Func([], [ProgressReport], ['query']),
  'getResume' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
  'getSkillGapAnalysis' : IDL.Func([], [SkillGapResult], ['query']),
  'getStudyTopic' : IDL.Func([TopicId], [IDL.Opt(StudyTopic)], ['query']),
  'getStudyTopics' : IDL.Func([UserRole], [IDL.Vec(StudyTopic)], ['query']),
  'getUserMockSessions' : IDL.Func([], [IDL.Vec(MockSession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTopicProgress' : IDL.Func(
      [],
      [IDL.Vec(UserTopicProgress)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTopicComplete' : IDL.Func([TopicId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
  'saveResume' : IDL.Func([ResumeInput], [ResumeData], []),
  'startMockSession' : IDL.Func(
      [UserRole, Difficulty],
      [SessionStartResult],
      [],
    ),
  'submitAnswer' : IDL.Func([SessionId, IDL.Text], [AnswerSubmitResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EducationEntry = IDL.Record({
    'gpa' : IDL.Opt(IDL.Text),
    'field' : IDL.Text,
    'startYear' : IDL.Nat,
    'endYear' : IDL.Opt(IDL.Nat),
    'institution' : IDL.Text,
    'degree' : IDL.Text,
  });
  const ExperienceEntry = IDL.Record({
    'title' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'company' : IDL.Text,
    'achievements' : IDL.Vec(IDL.Text),
    'startDate' : IDL.Text,
  });
  const ResumeInput = IDL.Record({
    'education' : IDL.Vec(EducationEntry),
    'experience' : IDL.Vec(ExperienceEntry),
    'summary' : IDL.Text,
    'targetRole' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ResumeData = IDL.Record({
    'userId' : UserId,
    'education' : IDL.Vec(EducationEntry),
    'experience' : IDL.Vec(ExperienceEntry),
    'summary' : IDL.Text,
    'updatedAt' : Timestamp,
    'targetRole' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const ResumeGenerationResult = IDL.Record({
    'resume' : ResumeData,
    'suggestions' : IDL.Vec(IDL.Text),
    'isDemo' : IDL.Bool,
    'keywords' : IDL.Vec(IDL.Text),
  });
  const ExperienceLevel = IDL.Variant({
    'Mid' : IDL.Null,
    'Junior' : IDL.Null,
    'Senior' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'ProductManager' : IDL.Null,
    'DataAnalyst' : IDL.Null,
    'DataScientist' : IDL.Null,
    'BackendDeveloper' : IDL.Null,
    'FrontendDeveloper' : IDL.Null,
    'FullStack' : IDL.Null,
    'DevOps' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'experienceLevel' : ExperienceLevel,
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'onboardingComplete' : IDL.Bool,
    'updatedAt' : Timestamp,
    'targetJobTitle' : IDL.Text,
  });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Hard' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const QuestionId = IDL.Nat;
  const ScoringRubric = IDL.Record({
    'fair' : IDL.Text,
    'good' : IDL.Text,
    'poor' : IDL.Text,
    'excellent' : IDL.Text,
  });
  const QuestionType = IDL.Variant({
    'Technical' : IDL.Null,
    'Behavioral' : IDL.Null,
  });
  const InterviewQuestion = IDL.Record({
    'id' : QuestionId,
    'idealAnswer' : IDL.Text,
    'question' : IDL.Text,
    'rubric' : ScoringRubric,
    'difficulty' : Difficulty,
    'role' : UserRole,
    'tags' : IDL.Vec(IDL.Text),
    'questionType' : QuestionType,
  });
  const SessionId = IDL.Nat;
  const MockSessionTurn = IDL.Record({
    'question' : IDL.Text,
    'userAnswer' : IDL.Text,
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'questionId' : QuestionId,
    'answeredAt' : Timestamp,
  });
  const MockSession = IDL.Record({
    'id' : SessionId,
    'completedAt' : IDL.Opt(Timestamp),
    'startedAt' : Timestamp,
    'turns' : IDL.Vec(MockSessionTurn),
    'userId' : UserId,
    'difficulty' : Difficulty,
    'role' : UserRole,
    'totalScore' : IDL.Nat,
    'questionIds' : IDL.Vec(QuestionId),
    'currentQuestionIndex' : IDL.Nat,
    'isComplete' : IDL.Bool,
  });
  const ScoreTrend = IDL.Record({
    'completedAt' : Timestamp,
    'score' : IDL.Nat,
    'sessionId' : SessionId,
  });
  const ProgressReport = IDL.Record({
    'scoreTrends' : IDL.Vec(ScoreTrend),
    'topicsTotal' : IDL.Nat,
    'readinessScore' : IDL.Nat,
    'skillsAcquired' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'lastUpdated' : Timestamp,
    'mockSessionsCompleted' : IDL.Nat,
    'topicsCompleted' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const TopicId = IDL.Nat;
  const StudyPlanItem = IDL.Record({
    'topicIds' : IDL.Vec(TopicId),
    'skill' : IDL.Text,
    'estimatedHours' : IDL.Nat,
    'priority' : IDL.Nat,
  });
  const SkillGapEntry = IDL.Record({
    'targetLevel' : IDL.Nat,
    'studyResources' : IDL.Vec(IDL.Text),
    'skill' : IDL.Text,
    'currentLevel' : IDL.Nat,
    'priority' : IDL.Nat,
  });
  const SkillGapResult = IDL.Record({
    'studyPlan' : IDL.Vec(StudyPlanItem),
    'weakSkills' : IDL.Vec(SkillGapEntry),
    'overallReadiness' : IDL.Nat,
  });
  const LearningLink = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'resourceType' : IDL.Text,
  });
  const Subtopic = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'links' : IDL.Vec(LearningLink),
  });
  const StudyTopic = IDL.Record({
    'id' : TopicId,
    'name' : IDL.Text,
    'role' : UserRole,
    'description' : IDL.Text,
    'subtopics' : IDL.Vec(Subtopic),
    'priority' : IDL.Nat,
  });
  const UserTopicProgress = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'completed' : IDL.Bool,
    'topicId' : TopicId,
  });
  const UserProfileInput = IDL.Record({
    'experienceLevel' : ExperienceLevel,
    'name' : IDL.Text,
    'role' : UserRole,
    'targetJobTitle' : IDL.Text,
  });
  const SessionStartResult = IDL.Record({
    'firstQuestion' : InterviewQuestion,
    'sessionId' : SessionId,
  });
  const AnswerSubmitResult = IDL.Record({
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'finalScore' : IDL.Opt(IDL.Nat),
    'nextQuestion' : IDL.Opt(InterviewQuestion),
    'sessionComplete' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'completeOnboarding' : IDL.Func([], [], []),
    'generateResume' : IDL.Func([ResumeInput], [ResumeGenerationResult], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getInterviewQuestions' : IDL.Func(
        [UserRole, IDL.Opt(Difficulty)],
        [IDL.Vec(InterviewQuestion)],
        ['query'],
      ),
    'getMockSession' : IDL.Func([SessionId], [IDL.Opt(MockSession)], ['query']),
    'getProgressReport' : IDL.Func([], [ProgressReport], ['query']),
    'getResume' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
    'getSkillGapAnalysis' : IDL.Func([], [SkillGapResult], ['query']),
    'getStudyTopic' : IDL.Func([TopicId], [IDL.Opt(StudyTopic)], ['query']),
    'getStudyTopics' : IDL.Func([UserRole], [IDL.Vec(StudyTopic)], ['query']),
    'getUserMockSessions' : IDL.Func([], [IDL.Vec(MockSession)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTopicProgress' : IDL.Func(
        [],
        [IDL.Vec(UserTopicProgress)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTopicComplete' : IDL.Func([TopicId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
    'saveResume' : IDL.Func([ResumeInput], [ResumeData], []),
    'startMockSession' : IDL.Func(
        [UserRole, Difficulty],
        [SessionStartResult],
        [],
      ),
    'submitAnswer' : IDL.Func([SessionId, IDL.Text], [AnswerSubmitResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };