/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudyPlanItem {
    topicIds: Array<TopicId>;
    skill: string;
    estimatedHours: bigint;
    priority: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserTopicProgress {
    completedAt?: Timestamp;
    userId: UserId;
    completed: boolean;
    topicId: TopicId;
}
export interface ScoreTrend {
    completedAt: Timestamp;
    score: bigint;
    sessionId: SessionId;
}
export interface InterviewQuestion {
    id: QuestionId;
    idealAnswer: string;
    question: string;
    rubric: ScoringRubric;
    difficulty: Difficulty;
    role: UserRole;
    tags: Array<string>;
    questionType: QuestionType;
}
export interface ResumeInput {
    education: Array<EducationEntry>;
    experience: Array<ExperienceEntry>;
    summary: string;
    targetRole: string;
    skills: Array<string>;
}
export interface ExperienceEntry {
    title: string;
    endDate?: string;
    description: string;
    company: string;
    achievements: Array<string>;
    startDate: string;
}
export interface EducationEntry {
    gpa?: string;
    field: string;
    startYear: bigint;
    endYear?: bigint;
    institution: string;
    degree: string;
}
export interface SkillGapResult {
    studyPlan: Array<StudyPlanItem>;
    weakSkills: Array<SkillGapEntry>;
    overallReadiness: bigint;
}
export type TopicId = bigint;
export interface ResumeGenerationResult {
    resume: ResumeData;
    suggestions: Array<string>;
    isDemo: boolean;
    keywords: Array<string>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MockSessionTurn {
    question: string;
    userAnswer: string;
    feedback: string;
    score: bigint;
    questionId: QuestionId;
    answeredAt: Timestamp;
}
export interface AnswerSubmitResult {
    feedback: string;
    score: bigint;
    finalScore?: bigint;
    nextQuestion?: InterviewQuestion;
    sessionComplete: boolean;
}
export interface Subtopic {
    name: string;
    description: string;
    links: Array<LearningLink>;
}
export interface ResumeData {
    userId: UserId;
    education: Array<EducationEntry>;
    experience: Array<ExperienceEntry>;
    summary: string;
    updatedAt: Timestamp;
    targetRole: string;
    skills: Array<string>;
}
export interface ProgressReport {
    scoreTrends: Array<ScoreTrend>;
    topicsTotal: bigint;
    readinessScore: bigint;
    skillsAcquired: Array<string>;
    userId: UserId;
    lastUpdated: Timestamp;
    mockSessionsCompleted: bigint;
    topicsCompleted: bigint;
    averageScore: bigint;
}
export interface ScoringRubric {
    fair: string;
    good: string;
    poor: string;
    excellent: string;
}
export interface SessionStartResult {
    firstQuestion: InterviewQuestion;
    sessionId: SessionId;
}
export interface LearningLink {
    url: string;
    title: string;
    resourceType: string;
}
export type QuestionId = bigint;
export type SessionId = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface StudyTopic {
    id: TopicId;
    name: string;
    role: UserRole;
    description: string;
    subtopics: Array<Subtopic>;
    priority: bigint;
}
export interface MockSession {
    id: SessionId;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    turns: Array<MockSessionTurn>;
    userId: UserId;
    difficulty: Difficulty;
    role: UserRole;
    totalScore: bigint;
    questionIds: Array<QuestionId>;
    currentQuestionIndex: bigint;
    isComplete: boolean;
}
export interface SkillGapEntry {
    targetLevel: bigint;
    studyResources: Array<string>;
    skill: string;
    currentLevel: bigint;
    priority: bigint;
}
export interface UserProfileInput {
    experienceLevel: ExperienceLevel;
    name: string;
    role: UserRole;
    targetJobTitle: string;
}
export interface UserProfile {
    experienceLevel: ExperienceLevel;
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    onboardingComplete: boolean;
    updatedAt: Timestamp;
    targetJobTitle: string;
}
export enum Difficulty {
    Easy = "Easy",
    Hard = "Hard",
    Medium = "Medium"
}
export enum ExperienceLevel {
    Mid = "Mid",
    Junior = "Junior",
    Senior = "Senior"
}
export enum QuestionType {
    Technical = "Technical",
    Behavioral = "Behavioral"
}
export enum UserRole {
    ProductManager = "ProductManager",
    DataAnalyst = "DataAnalyst",
    DataScientist = "DataScientist",
    BackendDeveloper = "BackendDeveloper",
    FrontendDeveloper = "FrontendDeveloper",
    FullStack = "FullStack",
    DevOps = "DevOps"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    completeOnboarding(): Promise<void>;
    generateResume(input: ResumeInput): Promise<ResumeGenerationResult>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getInterviewQuestions(role: UserRole, difficulty: Difficulty | null): Promise<Array<InterviewQuestion>>;
    getMockSession(sessionId: SessionId): Promise<MockSession | null>;
    getProgressReport(): Promise<ProgressReport>;
    getResume(): Promise<ResumeData | null>;
    getSkillGapAnalysis(): Promise<SkillGapResult>;
    getStudyTopic(topicId: TopicId): Promise<StudyTopic | null>;
    getStudyTopics(role: UserRole): Promise<Array<StudyTopic>>;
    getUserMockSessions(): Promise<Array<MockSession>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTopicProgress(): Promise<Array<UserTopicProgress>>;
    isCallerAdmin(): Promise<boolean>;
    markTopicComplete(topicId: TopicId): Promise<void>;
    saveCallerUserProfile(input: UserProfileInput): Promise<UserProfile>;
    saveResume(input: ResumeInput): Promise<ResumeData>;
    startMockSession(role: UserRole, difficulty: Difficulty): Promise<SessionStartResult>;
    submitAnswer(sessionId: SessionId, answer: string): Promise<AnswerSubmitResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnswerSubmitResult as _AnswerSubmitResult, Difficulty as _Difficulty, EducationEntry as _EducationEntry, ExperienceEntry as _ExperienceEntry, ExperienceLevel as _ExperienceLevel, InterviewQuestion as _InterviewQuestion, MockSession as _MockSession, MockSessionTurn as _MockSessionTurn, QuestionId as _QuestionId, QuestionType as _QuestionType, ResumeData as _ResumeData, ResumeGenerationResult as _ResumeGenerationResult, ResumeInput as _ResumeInput, ScoringRubric as _ScoringRubric, SessionId as _SessionId, SessionStartResult as _SessionStartResult, StudyTopic as _StudyTopic, Subtopic as _Subtopic, Timestamp as _Timestamp, TopicId as _TopicId, UserId as _UserId, UserProfile as _UserProfile, UserProfileInput as _UserProfileInput, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserTopicProgress as _UserTopicProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeOnboarding(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding();
            return result;
        }
    }
    async generateResume(arg0: ResumeInput): Promise<ResumeGenerationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.generateResume(to_candid_ResumeInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResumeGenerationResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateResume(to_candid_ResumeInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResumeGenerationResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterviewQuestions(arg0: UserRole, arg1: Difficulty | null): Promise<Array<InterviewQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterviewQuestions(to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterviewQuestions(to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockSession(arg0: SessionId): Promise<MockSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockSession(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockSession(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressReport(): Promise<ProgressReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressReport();
            return result;
        }
    }
    async getResume(): Promise<ResumeData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkillGapAnalysis(): Promise<SkillGapResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillGapAnalysis();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillGapAnalysis();
            return result;
        }
    }
    async getStudyTopic(arg0: TopicId): Promise<StudyTopic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyTopic(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyTopic(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyTopics(arg0: UserRole): Promise<Array<StudyTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyTopics(to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyTopics(to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMockSessions(): Promise<Array<MockSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMockSessions();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMockSessions();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTopicProgress(): Promise<Array<UserTopicProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTopicProgress();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTopicProgress();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markTopicComplete(arg0: TopicId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTopicComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTopicComplete(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveResume(arg0: ResumeInput): Promise<ResumeData> {
        if (this.processError) {
            try {
                const result = await this.actor.saveResume(to_candid_ResumeInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResumeData_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveResume(to_candid_ResumeInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResumeData_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async startMockSession(arg0: UserRole, arg1: Difficulty): Promise<SessionStartResult> {
        if (this.processError) {
            try {
                const result = await this.actor.startMockSession(to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg0), to_candid_Difficulty_n35(this._uploadFile, this._downloadFile, arg1));
                return from_candid_SessionStartResult_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startMockSession(to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg0), to_candid_Difficulty_n35(this._uploadFile, this._downloadFile, arg1));
            return from_candid_SessionStartResult_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAnswer(arg0: SessionId, arg1: string): Promise<AnswerSubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1);
                return from_candid_AnswerSubmitResult_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1);
            return from_candid_AnswerSubmitResult_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AnswerSubmitResult_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerSubmitResult): AnswerSubmitResult {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_EducationEntry_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationEntry): EducationEntry {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceEntry_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceEntry): ExperienceEntry {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceLevel_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewQuestion_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewQuestion): InterviewQuestion {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_MockSession_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MockSession): MockSession {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ResumeData_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResumeData): ResumeData {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ResumeGenerationResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResumeGenerationResult): ResumeGenerationResult {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStartResult_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStartResult): SessionStartResult {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_StudyTopic_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyTopic): StudyTopic {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserTopicProgress_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserTopicProgress): UserTopicProgress {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MockSession]): MockSession | null {
    return value.length === 0 ? null : from_candid_MockSession_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResumeData]): ResumeData | null {
    return value.length === 0 ? null : from_candid_ResumeData_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyTopic]): StudyTopic | null {
    return value.length === 0 ? null : from_candid_StudyTopic_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InterviewQuestion]): InterviewQuestion | null {
    return value.length === 0 ? null : from_candid_InterviewQuestion_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resume: _ResumeData;
    suggestions: Array<string>;
    isDemo: boolean;
    keywords: Array<string>;
}): {
    resume: ResumeData;
    suggestions: Array<string>;
    isDemo: boolean;
    keywords: Array<string>;
} {
    return {
        resume: from_candid_ResumeData_n13(_uploadFile, _downloadFile, value.resume),
        suggestions: value.suggestions,
        isDemo: value.isDemo,
        keywords: value.keywords
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    education: Array<_EducationEntry>;
    experience: Array<_ExperienceEntry>;
    summary: string;
    updatedAt: _Timestamp;
    targetRole: string;
    skills: Array<string>;
}): {
    userId: UserId;
    education: Array<EducationEntry>;
    experience: Array<ExperienceEntry>;
    summary: string;
    updatedAt: Timestamp;
    targetRole: string;
    skills: Array<string>;
} {
    return {
        userId: value.userId,
        education: from_candid_vec_n15(_uploadFile, _downloadFile, value.education),
        experience: from_candid_vec_n20(_uploadFile, _downloadFile, value.experience),
        summary: value.summary,
        updatedAt: value.updatedAt,
        targetRole: value.targetRole,
        skills: value.skills
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gpa: [] | [string];
    field: string;
    startYear: bigint;
    endYear: [] | [bigint];
    institution: string;
    degree: string;
}): {
    gpa?: string;
    field: string;
    startYear: bigint;
    endYear?: bigint;
    institution: string;
    degree: string;
} {
    return {
        gpa: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.gpa)),
        field: value.field,
        startYear: value.startYear,
        endYear: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.endYear)),
        institution: value.institution,
        degree: value.degree
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    endDate: [] | [string];
    description: string;
    company: string;
    achievements: Array<string>;
    startDate: string;
}): {
    title: string;
    endDate?: string;
    description: string;
    company: string;
    achievements: Array<string>;
    startDate: string;
} {
    return {
        title: value.title,
        endDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.endDate)),
        description: value.description,
        company: value.company,
        achievements: value.achievements,
        startDate: value.startDate
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: _ExperienceLevel;
    principal: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    onboardingComplete: boolean;
    updatedAt: _Timestamp;
    targetJobTitle: string;
}): {
    experienceLevel: ExperienceLevel;
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    onboardingComplete: boolean;
    updatedAt: Timestamp;
    targetJobTitle: string;
} {
    return {
        experienceLevel: from_candid_ExperienceLevel_n26(_uploadFile, _downloadFile, value.experienceLevel),
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.role),
        onboardingComplete: value.onboardingComplete,
        updatedAt: value.updatedAt,
        targetJobTitle: value.targetJobTitle
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    idealAnswer: string;
    question: string;
    rubric: _ScoringRubric;
    difficulty: _Difficulty;
    role: _UserRole;
    tags: Array<string>;
    questionType: _QuestionType;
}): {
    id: QuestionId;
    idealAnswer: string;
    question: string;
    rubric: ScoringRubric;
    difficulty: Difficulty;
    role: UserRole;
    tags: Array<string>;
    questionType: QuestionType;
} {
    return {
        id: value.id,
        idealAnswer: value.idealAnswer,
        question: value.question,
        rubric: value.rubric,
        difficulty: from_candid_Difficulty_n40(_uploadFile, _downloadFile, value.difficulty),
        role: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.role),
        tags: value.tags,
        questionType: from_candid_QuestionType_n42(_uploadFile, _downloadFile, value.questionType)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    completedAt: [] | [_Timestamp];
    startedAt: _Timestamp;
    turns: Array<_MockSessionTurn>;
    userId: _UserId;
    difficulty: _Difficulty;
    role: _UserRole;
    totalScore: bigint;
    questionIds: Array<_QuestionId>;
    currentQuestionIndex: bigint;
    isComplete: boolean;
}): {
    id: SessionId;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    turns: Array<MockSessionTurn>;
    userId: UserId;
    difficulty: Difficulty;
    role: UserRole;
    totalScore: bigint;
    questionIds: Array<QuestionId>;
    currentQuestionIndex: bigint;
    isComplete: boolean;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.completedAt)),
        startedAt: value.startedAt,
        turns: value.turns,
        userId: value.userId,
        difficulty: from_candid_Difficulty_n40(_uploadFile, _downloadFile, value.difficulty),
        role: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.role),
        totalScore: value.totalScore,
        questionIds: value.questionIds,
        currentQuestionIndex: value.currentQuestionIndex,
        isComplete: value.isComplete
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TopicId;
    name: string;
    role: _UserRole;
    description: string;
    subtopics: Array<_Subtopic>;
    priority: bigint;
}): {
    id: TopicId;
    name: string;
    role: UserRole;
    description: string;
    subtopics: Array<Subtopic>;
    priority: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.role),
        description: value.description,
        subtopics: value.subtopics,
        priority: value.priority
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: [] | [_Timestamp];
    userId: _UserId;
    completed: boolean;
    topicId: _TopicId;
}): {
    completedAt?: Timestamp;
    userId: UserId;
    completed: boolean;
    topicId: TopicId;
} {
    return {
        completedAt: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.completedAt)),
        userId: value.userId,
        completed: value.completed,
        topicId: value.topicId
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    firstQuestion: _InterviewQuestion;
    sessionId: _SessionId;
}): {
    firstQuestion: InterviewQuestion;
    sessionId: SessionId;
} {
    return {
        firstQuestion: from_candid_InterviewQuestion_n38(_uploadFile, _downloadFile, value.firstQuestion),
        sessionId: value.sessionId
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    feedback: string;
    score: bigint;
    finalScore: [] | [bigint];
    nextQuestion: [] | [_InterviewQuestion];
    sessionComplete: boolean;
}): {
    feedback: string;
    score: bigint;
    finalScore?: bigint;
    nextQuestion?: InterviewQuestion;
    sessionComplete: boolean;
} {
    return {
        feedback: value.feedback,
        score: value.score,
        finalScore: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.finalScore)),
        nextQuestion: record_opt_to_undefined(from_candid_opt_n65(_uploadFile, _downloadFile, value.nextQuestion)),
        sessionComplete: value.sessionComplete
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mid: null;
} | {
    Junior: null;
} | {
    Senior: null;
}): ExperienceLevel {
    return "Mid" in value ? ExperienceLevel.Mid : "Junior" in value ? ExperienceLevel.Junior : "Senior" in value ? ExperienceLevel.Senior : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ProductManager: null;
} | {
    DataAnalyst: null;
} | {
    DataScientist: null;
} | {
    BackendDeveloper: null;
} | {
    FrontendDeveloper: null;
} | {
    FullStack: null;
} | {
    DevOps: null;
}): UserRole {
    return "ProductManager" in value ? UserRole.ProductManager : "DataAnalyst" in value ? UserRole.DataAnalyst : "DataScientist" in value ? UserRole.DataScientist : "BackendDeveloper" in value ? UserRole.BackendDeveloper : "FrontendDeveloper" in value ? UserRole.FrontendDeveloper : "FullStack" in value ? UserRole.FullStack : "DevOps" in value ? UserRole.DevOps : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
}): Difficulty {
    return "Easy" in value ? Difficulty.Easy : "Hard" in value ? Difficulty.Hard : "Medium" in value ? Difficulty.Medium : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Technical: null;
} | {
    Behavioral: null;
}): QuestionType {
    return "Technical" in value ? QuestionType.Technical : "Behavioral" in value ? QuestionType.Behavioral : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EducationEntry>): Array<EducationEntry> {
    return value.map((x)=>from_candid_EducationEntry_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExperienceEntry>): Array<ExperienceEntry> {
    return value.map((x)=>from_candid_ExperienceEntry_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InterviewQuestion>): Array<InterviewQuestion> {
    return value.map((x)=>from_candid_InterviewQuestion_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyTopic>): Array<StudyTopic> {
    return value.map((x)=>from_candid_StudyTopic_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MockSession>): Array<MockSession> {
    return value.map((x)=>from_candid_MockSession_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserTopicProgress>): Array<UserTopicProgress> {
    return value.map((x)=>from_candid_UserTopicProgress_n55(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_EducationEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationEntry): _EducationEntry {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ExperienceEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceEntry): _ExperienceEntry {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ExperienceLevel_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_ResumeInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResumeInput): _ResumeInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileInput_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): _UserProfileInput {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty | null): [] | [_Difficulty] {
    return value === null ? candid_none() : candid_some(to_candid_Difficulty_n35(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    endDate?: string;
    description: string;
    company: string;
    achievements: Array<string>;
    startDate: string;
}): {
    title: string;
    endDate: [] | [string];
    description: string;
    company: string;
    achievements: Array<string>;
    startDate: string;
} {
    return {
        title: value.title,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        description: value.description,
        company: value.company,
        achievements: value.achievements,
        startDate: value.startDate
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    education: Array<EducationEntry>;
    experience: Array<ExperienceEntry>;
    summary: string;
    targetRole: string;
    skills: Array<string>;
}): {
    education: Array<_EducationEntry>;
    experience: Array<_ExperienceEntry>;
    summary: string;
    targetRole: string;
    skills: Array<string>;
} {
    return {
        education: to_candid_vec_n5(_uploadFile, _downloadFile, value.education),
        experience: to_candid_vec_n8(_uploadFile, _downloadFile, value.experience),
        summary: value.summary,
        targetRole: value.targetRole,
        skills: value.skills
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: ExperienceLevel;
    name: string;
    role: UserRole;
    targetJobTitle: string;
}): {
    experienceLevel: _ExperienceLevel;
    name: string;
    role: _UserRole;
    targetJobTitle: string;
} {
    return {
        experienceLevel: to_candid_ExperienceLevel_n59(_uploadFile, _downloadFile, value.experienceLevel),
        name: value.name,
        role: to_candid_UserRole_n32(_uploadFile, _downloadFile, value.role),
        targetJobTitle: value.targetJobTitle
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gpa?: string;
    field: string;
    startYear: bigint;
    endYear?: bigint;
    institution: string;
    degree: string;
}): {
    gpa: [] | [string];
    field: string;
    startYear: bigint;
    endYear: [] | [bigint];
    institution: string;
    degree: string;
} {
    return {
        gpa: value.gpa ? candid_some(value.gpa) : candid_none(),
        field: value.field,
        startYear: value.startYear,
        endYear: value.endYear ? candid_some(value.endYear) : candid_none(),
        institution: value.institution,
        degree: value.degree
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    ProductManager: null;
} | {
    DataAnalyst: null;
} | {
    DataScientist: null;
} | {
    BackendDeveloper: null;
} | {
    FrontendDeveloper: null;
} | {
    FullStack: null;
} | {
    DevOps: null;
} {
    return value == UserRole.ProductManager ? {
        ProductManager: null
    } : value == UserRole.DataAnalyst ? {
        DataAnalyst: null
    } : value == UserRole.DataScientist ? {
        DataScientist: null
    } : value == UserRole.BackendDeveloper ? {
        BackendDeveloper: null
    } : value == UserRole.FrontendDeveloper ? {
        FrontendDeveloper: null
    } : value == UserRole.FullStack ? {
        FullStack: null
    } : value == UserRole.DevOps ? {
        DevOps: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
} {
    return value == Difficulty.Easy ? {
        Easy: null
    } : value == Difficulty.Hard ? {
        Hard: null
    } : value == Difficulty.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    Mid: null;
} | {
    Junior: null;
} | {
    Senior: null;
} {
    return value == ExperienceLevel.Mid ? {
        Mid: null
    } : value == ExperienceLevel.Junior ? {
        Junior: null
    } : value == ExperienceLevel.Senior ? {
        Senior: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EducationEntry>): Array<_EducationEntry> {
    return value.map((x)=>to_candid_EducationEntry_n6(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExperienceEntry>): Array<_ExperienceEntry> {
    return value.map((x)=>to_candid_ExperienceEntry_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
